name: Build release
on:
  release:
    types: [created]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v2
        with:
          java-version: '11'
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Build template with sublate
        run: |
          pip install -r requirements.txt
          python build.py .
      - name: Build java package
        run: gradle buildPlugin
      - name: Get package name
        run: echo pkg_file=$(ls ./build/libs | head -n 1) >> $GITHUB_ENV
      - name: Upload to GH releases
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: ./build/libs/${{ env.pkg_file }}
          asset_name: ${{ env.pkg_file }}
          asset_content_type: application/java-archive
